### PR TITLE
new measures & units required by CM infofile importer

### PR DESCRIPTION
**Pull request by dmbarry86**
Added new measures and unit conversions required by CarMaker infofile importer. Unit test suite updated accordingly.

* Capacitance - F
* Charge - As, Ah
* Damping - Ns/m
* Fluid Density - kg/m3, kg/l
* Fluid Viscosity - m2/s, mm2/s
* Line Volume - Pa/m3, bar/cm3
* Resistance - Ohm
* Torque Conversion Factor - Nms2/rad2

### CODE REVIEW

**Comment by nicolasschwarz** [comment]
Looks good to me. There's actually another parameter that @AdrianSchoellhorn has pointed out. 
We are currently investigating with the CM development team, whether the CM 8 "Nms2" or CM 10 "Nms2/rad2" unit is correct for the parameter TRM.Automatic.Converter.FactorKE1D.
As both are missing currently in the list of units, I suggest we wait with merging this branch, if that's ok for you @dmbarry86

**Comment by dmbarry86** [comment]
Ok. Let me know.

**Comment by dmbarry86** [comment]
@bogotm there may be a short delay with the infofile reader pull request I asked you to review. It's now waiting on feedback from this one which it depends on. Hopefully will still be in this week for you to review before holiday.

**Comment by AdrianSchoellhorn** [comment]
Hi @dmbarry86 @nicolasschwarz, just found out this is a issue already reported and fixed since CM9:
grafik

So I'll change the unit in the parameter file accordingly. However, this will mean that the unit on NGD and CM8.X will not align. @nicolasschwarz is it possible to hard-code this change only for CM8 in the composer (so Nms²/rad² will be changed back to Nms²) or will it work if we just will in the table when we generate an infofile for CM8?

**Comment by nicolasschwarz** [comment]
@AdrianSchoellhorn thanks for getting that result so quickly.  For composer, no changes are necessary because the unit was only displayed wrong in the CM GUI, the values stay the same.
If we add the unit  "Nms2/rad2" to the NGD list of units/conversions and I change the mapping for the infofile reader tool, then we should be settled.

**Comment by AdrianSchoellhorn** [comment]
Updated parameters file: https://github.com/IPG-Automotive-UK/ngd/pull/519

**Comment by dmbarry86** [comment]
I've added the new measure/unit for torque conversion factor. Please can you re-review @nicolasschwarz.

**Review by nicolasschwarz — APPROVED** [review]
Changes look good to me

**Pull request merged**
